### ISSUE TITLE
MSP ADC Driver

### ISSUE THREAD

**Issue by silvehh** [scsd-cdh/OBC#12]
Just be able to implement basic ADC operations. AKA simply just be able to read analog from a pin

**Comment by Siri2K** [comment]
Hey @hanlee53 , did you start the ADC and GPIO driver thing on Saturday? I'm seeing a commit from me that has both ADC and GPIO already done? I haven't touched the code till now

**Comment by Siri2K** [comment]
Nvm, Amro filled me on what happened with the commit

**Comment by silvehh** [comment]
Finished this issue, ADC driver ready
