### ISSUE TITLE
MSP Voltage Monitoring (ADC)

### ISSUE THREAD

**Issue by silvehh** [scsd-cdh/OBC#13]
Logically Preceding Issue: #12 

Be able to monitor the voltage of a pin by digitally converting analog signals. AKA read analog signal from a pin and display the reading

**Comment by Siri2K** [comment]
Hey @jasminetheepeach, did you start the ADC and GPIO driver thing on Saturday? I'm seeing a commit from me that has both ADC and GPIO already done? I haven't touched the code till now

**Comment by Siri2K** [comment]
Just wanna know so I can close the issue and move to the next step

**Comment by Siri2K** [comment]
Nvm, Amro filled me on what happened with the commit

**Comment by jasminetheepeach** [comment]
Hey @Siri2K , I was thinking of coming in on Saturday at 2:00 to work on this. Is that okay with you? I could also come in sometime Thursday - Friday as well.

**Comment by Siri2K** [comment]
Hi @jasminetheepeach ,

I made a code last week for the ADC driver and voltage reading. We can test it out Friday. I'll be at school and I can test with u the code from 11 to 2

**Comment by jasminetheepeach** [comment]
That sounds good to me!

**Comment by Siri2K** [comment]
Hey @jasminetheepeach lmk if you're able to get in the lab? When I tried, the room was locked

**Comment by jasminetheepeach** [comment]
@Siri2K no I wasn't able to get in I tried earlier, but I left a few minutes ago

**Comment by Siri2K** [comment]
U wanna meetup and go over the code together?

**Comment by jasminetheepeach** [comment]
I'm studying at McGill with my boyfriend right now, but I can come back for a bit. Where would you like to meet?

**Comment by Siri2K** [comment]
Probably better if we check around 1 if the room is open. If not, we can test after the exams are over

**Comment by jasminetheepeach** [comment]
Okay that sounds good to me. I'll head over then.

**Comment by jasminetheepeach** [comment]
I'm gonna be a bit late. I'll probably arrive around 1:15
